### ISSUE TITLE
Subnets creation mechanism

### ISSUE THREAD

**Issue by BastienM** [d2si-oss/terraform-modules#10]
Using `azs_count` plus `public_subnet_blocks`with several cidr has not the behavior I thought it would have.

### What I was expecting
Creation of each specified subnet (blocks) in into different AZ (a,b,c)

### What happened
In this case, it splits each block by the number of `azs_count` (with a /26 mask) into each AZ (a,b,c), multiplied by the number of items in `public_subnet_blocks` / `private_subnet_blocks`.

Example [here](https://0bin.net/paste/vSXvV560czCPdGp4#zZ72O9EiNUnyvT6nH687nOuKzfCRsCBmQRjuzc1X+2E).

**Comment by lbernail** [comment]
This is by design: you provide block for each subnet "role" and this block is divided based on the number of availability zones (in the region or chosen in the configuration)
This is usually what is needed and simplifies network configuration

**Comment by BastienM** [comment]
That is a bit counter-intuitive as you'll need to declare three subnets to have full /24 range available on each availability zone but that's ok (and comprehensible).

Adding more depth to the part of the documentation speaking about how the variable `azs-count` changes the behavior of subnet handling would be welcome in that case.

**Comment by lbernail** [comment]
If you want a /24 in two AZ for a public role (DMZ for instance), you simply have to do:

```
module "backbone" {
  source                = "github.com/d2si-oss/terraform-modules//aws/backbone"
  vpc_cidr              = "10.0.0.0/16"
  public_subnet_blocks  = ["10.0.0.0/23"]
  public_subnet_names   = ["DMZ"]
  azs_count =2
}
```
This will generate:
- subnet 10.0.0.0/24 in az a
- subnet 10.0.0.1/24 in az b

If you have 3 AZ, you will need to use a larger block
```
module "backbone" {
  source                = "github.com/d2si-oss/terraform-modules//aws/backbone"
  vpc_cidr              = "10.0.0.0/16"
  public_subnet_blocks  = ["10.0.0.0/22"]
  public_subnet_names   = ["DMZ"]
  azs_count = 3
}
```
This will generate:
- subnet 10.0.0.0/24 in az a
- subnet 10.0.0.1/24 in az b
- subnet 10.0.0.2/24 in az c

Is it clearer?

**Comment by BastienM** [comment]
Yes, much clearer like that.
I didn't thought about using a larger block to solve this.

If something like that could appear natural for some of us, that might not be the case for everyone. I am highly in favor of putting it in the documentation or creating a new example with the usage of `azs_count`.
