### ISSUE TITLE
Version the project

### ISSUE THREAD

**Issue by Ninir** [d2si-oss/terraform-modules#7]
Versionning the modules would allow users to get the exact same behaviour when `terraform get`-ing them at different point of times, for a same project.

This is an idea taken from https://blog.gruntwork.io/how-to-create-reusable-infrastructure-with-terraform-modules-25526d65f73d, which would allow such declaration:

```
module "frontend" {
  source = "git::git@github.com:gruntwork-io/infrastructure-modules.git//frontend-app?ref=v0.0.2"
  min_size = 1
  max_size = 2
}
```

**Comment by ajacoutot** [comment]
Yes, this will eventually become a requirement sooner than later.
Thanks.
